### ISSUE TITLE
Memory leak in http2 module (version=2.4.3)

### ISSUE THREAD

**Issue by lcybo** [eclipse-ee4j/glassfish-grizzly#2020]
Hi, 

When I do performance test, memory leak issue is encountered:
![debug](https://user-images.githubusercontent.com/15042781/46129319-dde59c80-c268-11e8-95dc-a1102db84ed7.PNG)

- It seems the state of every closed stream in streamsMap is always 'OPEN'.

- Breakpoint is suspend with condition (isGoingAway() == true), as picture shows, concurrentStreamsCount == -1. As a result, Http2Session could not be closed. PS: closeFlag == REMOTELY

Class Name | Shallow Heap | Retained Heap | Percentage
-- | -- | -- | --
org.glassfish.grizzly.http2.Http2Session @ 0x73f80d430 | 160 | 291,645,704 | 88.96%
java.util.TreeMap @ 0x73f80fe28 | 48 | 291,640,408 | 88.95%
java.util.TreeMap$Entry @ 0x73f80fe58 | 40 | 291,640,344 | 88.95%
java.util.TreeMap$Entry @ 0x7385858f8 | 40 | 225,062,840 | 68.65%
java.util.TreeMap$Entry @ 0x7349b71b8 | 40 | 157,161,176 | 47.94%
java.util.TreeMap$Entry @ 0x73e3f47b8 | 40 | 67,893,352 | 20.71%
org.glassfish.grizzly.http2.Http2Stream @ 0x738585930 | 80 | 8,256 | 0.00%
java.lang.Integer @ 0x738585920  32767 | 16 | 16 | 0.00%
Total: 4 entries | 176 | 225,062,800 | 68.65%

**Comment by antsfiles** [comment]
I think i found out too that Payara 5 (183 and 184), Glassfish5, and event Wildfly 15 are impacted by a memory leak due to grizzly and http2.

**Comment by svendiedrichsen** [comment]
@lcybo Would you mind testing #2033 for confirmation?
