### ISSUE TITLE
Shutting down the server does not call @PreDestroy annotated resource methods

### ISSUE THREAD

**Issue by Jilocasin** [eclipse-ee4j/glassfish-grizzly#2024]
When shutting down a Grizzly HTTP server by calling `shutdownNow()` it seems that the @PreDestroy method of all (internally on-demand instantiated) resources is NOT called.

In my example those resources internally manage a `Timer` instance, which is created and stopped in the @PostConstruct/@PreDestroy methods. Because the timer is never stopped its background thread keeps the JVM running even after the server has already been shut down. I would have suspected all resources to be properly destroyed as well.

Please refer to this Stackoverflow question for more details: https://stackoverflow.com/questions/53067164/jersey-resource-predestroy-not-getting-called-when-grizzley-server-is-shut-down

Versions used:
- jersey-container-grizzly2-http: 2.27
- grizzly-http-server: 2.4.0 (dependency from above)

**Comment by jansohn** [comment]
Just run into the same problem. Have you ever found a solution?

EDIT: I think I found a workaround by removing the default network listener before shutting down...

```java
httpServer.removeListener("grizzly");
```

I still think this should be fixed properly though...
