### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-grizzly#2027]
- [x] Integrate to Eclipse GlassFish
- [x] Pass all CTS/TCK tests

#2025 must be finished before starting working on this task.

**Comment by anajosep** [comment]
Submitted this PR to integrate Eclipse Grizzly 2.4.4 and Eclipse Grizzly NPN 1.9 to Eclipse GlassFish
https://github.com/eclipse-ee4j/glassfish/pull/22650

**Comment by anajosep** [comment]
The PR is merged. The CTS/TCK certification is pending.

**Comment by anajosep** [comment]
If there are any new/additional CTS test failures whose root cause if suspected to be caused by the new version of Grizzly, I would be filing a separate tracking bug for the same. Closing this issue.
