### ISSUE TITLE
Framework occupying huge VIRT memory in Redhat OS

### ISSUE THREAD

**Issue by kumark-pk** [eclipse-ee4j/glassfish-grizzly#2030]
I encountered strange issue while using grizzly framework on the redhot boxes. 

On start of the Http server, huge number of threads by name -  **_grizzly-http-server (*)  / grizzly-nio-kernel(*) SelectorRunner._** getting created. 

For reference, please see the thread dump - [Thread-Dump.log](https://github.com/eclipse-ee4j/grizzly/files/2639682/Thread-Dump.log)

The job tried to ran in the below system configuration 
OS - Red Hat Enterprise Linux Server release 6.7 (Santiago)
Grizzly Version - 2.4.3.1 / 2.4.2 / 2.4.0 / 2.3.28
Java - jdk1.8.0_121

The VIRT memory it tooks ranges from 15g to 23g

I don't find any issue if I ran in Oracle / CentOS  boxes.

Thanks and Regards,
Kranthi

**Comment by svendiedrichsen** [comment]
@kumark-pk Could you please try a different MemoryManager by setting the system property. Please see: https://javaee.github.io/grizzly/memory.html

Maybe this is just the wrong way of looking at the memory consumption. Please see https://stackoverflow.com/questions/561245/virtual-memory-usage-from-java-under-linux-too-much-memory-used
