### ISSUE TITLE
Update Grizzly project page

### ISSUE THREAD

**Issue by psuzzi** [eclipse-ee4j/glassfish-grizzly#2069]
The following grizzly project page is outdated: https://javaee.github.io/grizzly/contribute.html

1. The page still mentions the Oracle Contributor Agreement, and this is inconsistent w.r.t. information reported in https://github.com/eclipse-ee4j/grizzly/blob/master/CONTRIBUTING.md
2. The page says the project activity is temporarily paused for the transition, but the status page says the transition of Grizzly is 100% done. See: https://www.eclipse.org/ee4j/status.php
3. License terms still reference Oracle, i.e. "You hereby grant to Oracle and all Users a royalty-free, perpetual, irrevocable..". There should be a refrence to Eclipse

**Comment by edbratt** [comment]
Thank you for filing this issue. Two things: This project has been archived and is not actively soliciting, nor accepting contributions. To contribute to Grizzly, please see: https://github.com/eclipse-ee4j/grizzly. I trust you will find all the associated meta-data there, up to date and we'd welcome your contributions to that Eclipse based project.
