### ISSUE TITLE
Method org.glassfish.grizzly.servlet.HttpServletRequestImpl.authenticate is not implemented

### ISSUE THREAD

**Issue by markusweisssiemens** [eclipse-ee4j/glassfish-grizzly#2071]
Are there any plans to implement the Jaspic methods:

- authenticate
- login 
- logout

?

**Comment by arjantijms** [comment]
I'd say this should be in the plans indeed. Today AFAIK the Servlet implementation of Grizzly is not complete, but one day it should be.

**Comment by smillidge** [comment]
They should do something but there would need to be an SPI to plug in a security provider. Adding a security provider to Grizzly would be beyond its remit.
