### ISSUE TITLE
Java 11, TLSv1.3 hotloop in SelectorRunner Threads

### ISSUE THREAD

**Issue by mduft** [eclipse-ee4j/glassfish-grizzly#2075]
After we upgraded to Java 11, we had the issue that our software was barely running 5 minutes under load until grizzly's SelectorRunner threads were exhausted. All of them were busy (100% CPU) with a stacktrace like this:

```
"grizzly-nio-kernel(1) SelectorRunner" #27 daemon prio=5 os_prio=0 cpu=1875910.87ms elapsed=4991.04s tid=0x00007f76410c7800 nid=0xf55 runnable  [0x00007f75fd4d0000]
   java.lang.Thread.State: RUNNABLE
	at sun.security.ssl.SSLEngineImpl.writeRecord(java.base@11.0.4/SSLEngineImpl.java:253)
	at sun.security.ssl.SSLEngineImpl.wrap(java.base@11.0.4/SSLEngineImpl.java:136)
	- eliminated <0x0000000082b35dd0> (a sun.security.ssl.SSLEngineImpl)
	at sun.security.ssl.SSLEngineImpl.wrap(java.base@11.0.4/SSLEngineImpl.java:116)
	- locked <0x0000000082b35dd0> (a sun.security.ssl.SSLEngineImpl)
	at javax.net.ssl.SSLEngine.wrap(java.base@11.0.4/SSLEngine.java:479)
	at org.glassfish.grizzly.ssl.SSLUtils.sslEngineWrap(SSLUtils.java:427)
	at org.glassfish.grizzly.ssl.SSLConnectionContext.wrap(SSLConnectionContext.java:337)
	at org.glassfish.grizzly.ssl.SSLUtils.handshakeWrap(SSLUtils.java:303)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:673)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeSync(SSLBaseFilter.java:577)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.silentRehandshake(SSLBaseFilter.java:796)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.unwrapAll(SSLBaseFilter.java:413)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:293)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        ...
```

The threads never escaped `SSLBaseFilter.doHandshakeStep`. After calling `handshakeWrap`, `getHandshakeStatus` *immediately* returned `NEED_WRAP` again, so it looped. All SelectorRunners did so.

AFAICT there were no more open connections to the server when this happened (I even closed the browser). The amount of load/connections to reproduce this was rather small. It was a simple server, serving a few REST endpoints for a web application. ~100 requests from a single browser was enough to put at least some of the threads into this state.

We disabled TLSv1.3 for now using `sslEngine.setEnabledProtocols(new String[] { "TLSv1", "TLSv1.1", "TLSv1.2" });`. This seems to work around the issue for now.

**Comment by psx88** [comment]
We have the same issue. Upgrading to JDK 12 helped. But upgrading till the release of Java 17 LTS in 2021 isn't really an option.
Thanks to @mduft . I appreciate your workaround. I hope this will be fixed soon.

**Comment by mich9463** [comment]
We also have the same issue.  We're using Tyrus, the Java reference implementation of Websockets, which in turn uses  grizzly-framework.2.4.4.jar.

When we connect to a wss:// endpoint, everything is ok.  Upon disconnecting, one of the Grizzly threads gets stuck in the same hot loop described above.

Unfortunately, using `sslEngineConfigurator.setEnabledProtocols(new String[] { "TLSv1", "TLSv1.1", "TLSv1.2" })` does not change anything for us.

**Comment by mich9463** [comment]
There are several unit test failures in the SSL area when running `mvn test`

```
[ERROR] Failures:
[ERROR]   TCPNIOTransportTest.testThreadInterruptionDuringAcceptDoesNotMakeServerDeaf:420
[ERROR] Errors:
[ERROR]   SSLTest.test20on1PendingSSLClientWrites:226->doTestPendingSSLClientWrites:619 » Bind
[ERROR]   SSLTest.test5PacketsOn1ConnectionAsyncSSL:164->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn1ConnectionAsyncSSL:164->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn1ConnectionAsyncSSL:164->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn1ConnectionAsyncSSL:164->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn1ConnectionSyncSSL:159->doTestSSL:528 » Runtime Invalid ...
[ERROR]   SSLTest.test5PacketsOn1ConnectionSyncSSL:159->doTestSSL:528 » Runtime Invalid ...
[ERROR]   SSLTest.test5PacketsOn1ConnectionSyncSSL:159->doTestSSL:528 » Runtime Invalid ...
[ERROR]   SSLTest.test5PacketsOn1ConnectionSyncSSL:159->doTestSSL:528 » Runtime Invalid ...
[ERROR]   SSLTest.test5PacketsOn5ConnectionsAsyncSSL:174->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn5ConnectionsAsyncSSL:174->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn5ConnectionsAsyncSSL:174->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn5ConnectionsAsyncSSL:174->doTestSSL:531 » Timeout
[ERROR]   SSLTest.test5PacketsOn5ConnectionsSyncSSL:169->doTestSSL:528 » Runtime Invalid...
[ERROR]   SSLTest.test5PacketsOn5ConnectionsSyncSSL:169->doTestSSL:528 » Runtime Invalid...
[ERROR]   SSLTest.test5PacketsOn5ConnectionsSyncSSL:169->doTestSSL:528 » Runtime Invalid...
[ERROR]   SSLTest.test5PacketsOn5ConnectionsSyncSSL:169->doTestSSL:528 » Runtime Invalid...
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedAfter:194->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedAfter:194->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedAfter:194->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedAfter:194->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedBefore:184->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedBefore:184->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedBefore:184->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSLChunkedBefore:184->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSL:154->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSL:154->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSL:154->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleAsyncSSL:154->doTestSSL:531 » Timeout
[ERROR]   SSLTest.testSimpleSyncSSLChunkedAfter:189->doTestSSL:528 » Runtime Invalid Han...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedAfter:189->doTestSSL:528 » Runtime Invalid Han...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedAfter:189->doTestSSL:528 » Runtime Invalid Han...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedAfter:189->doTestSSL:528 » Runtime Invalid Han...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedBefore:179->doTestSSL:528 » Runtime Invalid Ha...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedBefore:179->doTestSSL:528 » Runtime Invalid Ha...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedBefore:179->doTestSSL:528 » Runtime Invalid Ha...
[ERROR]   SSLTest.testSimpleSyncSSLChunkedBefore:179->doTestSSL:528 » Runtime Invalid Ha...
[ERROR]   SSLTest.testSimpleSyncSSL:149->doTestSSL:528 » Runtime Invalid Handshaking Sta...
[ERROR]   SSLTest.testSimpleSyncSSL:149->doTestSSL:528 » Runtime Invalid Handshaking Sta...
[ERROR]   SSLTest.testSimpleSyncSSL:149->doTestSSL:528 » Runtime Invalid Handshaking Sta...
[ERROR]   SSLTest.testSimpleSyncSSL:149->doTestSSL:528 » Runtime Invalid Handshaking Sta...
[INFO]
[ERROR] Tests run: 363, Failures: 1, Errors: 41, Skipped: 8
```

$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

**Comment by psx88** [comment]
@mich9463 When I remember correctly I had given up on the Java 11 TLS issue. The problems started with an early version of OpenJDK 11. After discovering I was already on the latest available OpenJDK Version and was testing other Java 11 vendors like Zulu Community. Same issue so I went on and upgraded to Java 12. Problem solved, but I wasn't pleased about the ongoing upgrades of Java till something isn't compatible with the current libraries and breaks the production. I swear the fix wasn't working on the early Java 11 version or I messed up with the protocol versions of the array.

I'm still using a php server with a simple script to reverse proxy to an api endpoint of our production server. With this I was reproducing the issue. It still happens on the latest 11.0.4 without the fix, but with the fix on this version the issue is gone.

**Comment by mich9463** [comment]
The problem disappears when running on:

$ ./java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

**Comment by mpfz0r** [comment]
This seems to finally got fixed with openjdk `11.0.8`
https://bugs.openjdk.java.net/browse/JDK-8209333

**Comment by mpfz0r** [comment]
And funny enough that bug got revived with Java 8 `8u262` when they added TLSv1.3 support.

However, the workaround that solves this issue for any Java version is using
`-Djdk.tls.acknowledgeCloseNotify=true`

**Comment by mduft** [comment]
We no longer experience this issue with current JDK 11 versions, current grizzly version and current jersey version.
