### ISSUE TITLE
org.glassfish.grizzly.osgi.httpservice.Activator prints to System.out instead to the logger

### ISSUE THREAD

**Issue by pdolezal** [eclipse-ee4j/glassfish-grizzly#2080]
The activator for OSGi prints the used port to `System.out` instead of the logger (see method `startGrizzly`).

**Comment by smillidge** [comment]
Do you want to make a PR?

**Comment by pdolezal** [comment]
Thanks for asking. I have not signed for contribution yet and I guess that a single line is not worth waiting for me to handle it. Feel free to go ahead. But I'll try to dig through the contribution conditions, when I have some time, to be ready for the next time :wink:
