### ISSUE TITLE
It's possible use io_uring????

### ISSUE THREAD

**Issue by AngeloRubens** [eclipse-ee4j/glassfish-grizzly#2107]
Hi All, can possible to use io_uring in grizzly?

https://blogs.oracle.com/linux/an-introduction-to-the-io_uring-asynchronous-io-framework

https://kernel.dk/io_uring.pdf

**Comment by scholzi100** [comment]
Netty is currently working on an implementation: https://github.com/netty/netty-incubator-transport-io_uring
