### ISSUE TITLE
OSGi bundle error (reference to android.os in Import-Package)

### ISSUE THREAD

**Issue by senivam** [eclipse-ee4j/glassfish-grizzly#2108]
since Grizzly 3.0.0-M1 there is reference to android.os in import section of manifest.mf (grizzzly-framework, grizzly-http-server-core), this reference shall be marked at least as optional (if not totally removed), because this prevents from running Grizzly modules (with this reference) in OSGi environment.

**Comment by senivam** [comment]
@arjantijms could you please take a look?

**Comment by arjantijms** [comment]
Okay, let me take a look then. Wonder how that came to be.

**Comment by senivam** [comment]
thank you :) meanwhile I've found another OSGi error in grizzly/servlet module (jakarta.servlet API version is wrong), so, I've prepared a PR (#2109) which fixes issues I 've found. Hovever It is possible that there will be more redundand android.os occurences (but it is absent in most of modules I've checked), so it might require a deeper look :)

**Comment by arjantijms** [comment]
What I think might have caused this is the over-eager scanning of recent bind versions to try and find references to import from classes loaded dynamically. If you use `class.byname("foo.bar)`, bind will now pick up class "foo.bar". Quite annoying.

Bind itself has switches to turn this off, but the Maven plugin doesn't honour this yet.

**Comment by senivam** [comment]
yeah, that was my guess as well, because since the only change was plugin version update, the issue obviously appeared due to 'improvements' inside the plugin :)
