### ISSUE TITLE
Remove dependency on Grizzly NPN

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish-grizzly#2115]
As ALPN is now supported on all current JDK distributions based on OpenJDK since 8u252, the bootstrap is not needed any more.

See also this table on Jetty's website:
https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions

Also [Grizzly Bootstrap NPN](https://github.com/eclipse-ee4j/grizzly-npn) is not compilable on new JDK versions and at least for 8u265 and newer it cannot be easily fixed, while for older JDK versions there are alternatives like [OpenJSSE](https://github.com/openjsse/openjsse)

See also: https://bugs.openjdk.java.net/browse/JDK-8230977 and https://bugs.openjdk.java.net/browse/JDK-8233417

**Comment by arjantijms** [comment]
+1 please remove this indeed.
