### ISSUE TITLE
Manifests should contain automatic module names

### ISSUE THREAD

**Issue by manorrock** [eclipse-ee4j/glassfish-grizzly#2122]

**Comment by manorrock** [comment]
Any progress on this one?

**Comment by manorrock** [comment]
@arjantijms Is a PR needed to move this forward?

**Comment by smillidge** [comment]
A PR is good

**Comment by mnriem** [comment]
@smillidge @arjantijms What is the naming convention here?

**Comment by mnriem** [comment]
@smillidge @arjantijms  All core modules now have a module-info. All bundles do not. Not sure what the naming should be for the monitoring modules as they do not have a clear main package. Any thoughts?
