### ISSUE TITLE
Please support SameSite attribute in org.glassfish.grizzly.http.Cookie

### ISSUE THREAD

**Issue by technolion** [eclipse-ee4j/glassfish-grizzly#2123]
The `SameSite` attribute in set-cookie is supported by nearly all browsers but [Grizzly Cookie](https://github.com/eclipse-ee4j/grizzly/blob/bf2d3babfe95b4fcd993a0c3c17d205ca320c44c/modules/http/src/main/java/org/glassfish/grizzly/http/Cookie.java) does not support it yet.
Please add support for it.
https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by SCadilhac** [comment]
Hi @arjantijms, was this really completed? I cannot see the option in the code.
