### ISSUE TITLE
About "TemporarySelectorIO" in "NIOTransport" class. 

### ISSUE THREAD

**Issue by tcmot** [eclipse-ee4j/glassfish-grizzly#2130]
Hi,all
I'm reading the source code, I have a question.

Set a "temporary selector pool".

Like this:
` temporarySelectorIO.setSelectorPool(
                        new TemporarySelectorPool(selectorProvider,
                                              selectorPoolSize));`
The two classes associated with this class are as follows:
TemporarySelectorReader
TemporarySelectorWriter

I want to know when "TemporarySelectorPool" will be used.

I found that when "Transportcontext. Isblocking()=true", "TemporarySelectorPool" will be used.

Why?

What does that mean?

I can't understand what the purpose is.

If there is any offence, it is not my intention.

Thanks.

**Comment by jdklog** [comment]
By the way.

Is there a place to discuss the grizzly project?
