### ISSUE TITLE
Bot's email used to create commits in release jobs is not in sync with Eclipse infra data

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-grizzly#2137]
I suppose that build jobs in this project, for some reason, set git's `user.email`, like in https://ci.eclipse.org/grizzly/job/1_grizzly-npn-build-and-stage/11/console:
```
+ git config --global user.email eclipse-grizzly-bot@eclipse.org
```
However
```
$ curl https://api.eclipse.org/bots | jq '.[] | select(.projectId == "ee4j.grizzly") | .["github.com"].email'
"grizzly-bot@eclipse.org"
```

For example - commit https://github.com/eclipse-ee4j/grizzly/releases/tag/2.4.4 - was attributed to @eclipse-grizzly-bot, but it changed since.

**Comment by pzygielo** [comment]
How this was _completed_ when https://github.com/eclipse-ee4j/grizzly/commit/4bb259c81a340b19df79305a55a3677daa5f9760.patch still shows that the unmatched email address is used by Jenkins job?
![image](https://github.com/eclipse-ee4j/grizzly/assets/11896137/144ceccf-a52f-4307-b894-6855a8bab228)
unlike the previously
![image](https://github.com/eclipse-ee4j/grizzly/assets/11896137/b9623216-635b-4bc5-a286-c9ba0c0165dc)

**Comment by arjantijms** [comment]
> How this was _completed_ when https://github.com/eclipse-ee4j/grizzly/commit/4bb259c81a340b19df79305a55a3677daa5f9760.patch still shows that the unmatched email address is used by Jenkins job?
> ![image](https://private-user-images.githubusercontent.com/11896137/283986730-144ceccf-a52f-4307-b894-6855a8bab228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDY3MTksIm5iZiI6MTcwMzAwNjQxOSwicGF0aCI6Ii8xMTg5NjEzNy8yODM5ODY3MzAtMTQ0Y2VjY2YtYTUyZi00MzA3LWI4OTQtNjg1NWE4YmFiMjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE3MjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYjgyZDBjYTk4NWRjZjUzNjc1ZDhkZjUzNTVkZDJlNWQwYTU3ZjhiNzJlMWUyZTQ5NDRjY2U2ZTkxNWI1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRmduVCD6WkqC1CqR8GB9CB5uKPS5PA-UcOS73z4KTs)
> unlike the previously
> ![image](https://private-user-images.githubusercontent.com/11896137/283986791-b9623216-635b-4bc5-a286-c9ba0c0165dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDY3MTksIm5iZiI6MTcwMzAwNjQxOSwicGF0aCI6Ii8xMTg5NjEzNy8yODM5ODY3OTEtYjk2MjMyMTYtNjM1Yi00YmM1LWEyODYtYzliYTBjMDE2NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE3MjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODEzYTM2NzFmODcyODdmNDg4ZjE4NDkxNGQ1YmI0YTRjODdiYTcyZTczOGUzMDhmNzc2NjcwNjQ5MTJjMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kn3v2_ISoE0A8ygTpSHm1nZxUdCd4w6DlanzXZST7Bo)

Tbh, I don't know. But thanks again for keeping an eye on this. I just updated the email addresses for all jobs in the Release view.
