### ISSUE TITLE
Grizzly is not compatible with Servlet 6

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/glassfish-grizzly#2153]
jakarta.servlet.SingleThreadModel is no longer in Servlet 6 API.

For instance, [WebappContext](https://github.com/eclipse-ee4j/grizzly/blob/master/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java) is not compatible with Servlet 6.

**Comment by arjantijms** [comment]
Thanks for the reminder, that indeed still needs to be done.

That aside, I wonder btw if the half-finished Servlet implementation in Grizzly is really needed still. Is anyone really using this?

**Comment by jansupol** [comment]
Jersey is using it for the test framework. I think the Jersey test framework is also used by one of the spring boot modules.

**Comment by arjantijms** [comment]
Interesting. Did you ever try running the Servlet TCK against Grizzly to get an idea what percentage of the Servlet API is implemented?

And just curiously, but was it really the idea to turn Grizzly into a fully compliant Servlet implementation?

**Comment by jansupol** [comment]
As far as I remember, Alexey implemented just the minimum functionality for mocking the servlet deployment. It was never meant to be a full servlet implementation.

**Comment by lukasj** [comment]
metro needs grizzly as well in order to be fully buildable from sources, see https://github.com/eclipse-ee4j/metro-wsit/issues/155

**Comment by smillidge** [comment]
So is this issue just requesting a build with the Servlet API brought up to speed with Servlet 6 i.e. not an implementation but something you can compile against?

**Comment by lukasj** [comment]
from metro point of view - yes; should there be need for anything specific to be implemented, that can be done once we see real failure (ie metro uses grizzly for tcp level transport)

**Comment by jansupol** [comment]
This issue is about replacing the Servlet 5 deprecated methods that have been removed in Servlet 6 with methods that are not deprecated.

**Comment by dmatej** [comment]
Just FYI, I am working on that, I hope I will be able to push (first?) changes today.

**Comment by dmatej** [comment]
This issue can be closed now
