### ISSUE TITLE
Release Grizzly to Maven central

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/glassfish-grizzly#2167]
Any plan for releasing Grizzly to Maven Central?

Apparently, the [Release review was not scheduled](https://projects.eclipse.org/projects/ee4j.grizzly), yet.
To my knowledge, milestone versions do not need to wait for the release review and can be released to maven central.

Without Grizzly 4, projects like Jersey or Tyrus won't be able to be publicly released.

Thanks.

**Comment by arjantijms** [comment]
@jansupol If needed I can release [4.0.0-M2/](https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/grizzly/grizzly-core/4.0.0-M2/) right away to central. Let me know if that would help.

I'll also schedule the release review for 4.0.0, so we can release 4.0.0 next month.

**Comment by arjantijms** [comment]
@jansupol see https://projects.eclipse.org/projects/ee4j.grizzly/reviews/4.0.0-release-review

**Comment by kofemann** [comment]
@arjantijms would you conciser to incode https://github.com/eclipse-ee4j/grizzly/pull/2144 into 4.0?

**Comment by jansupol** [comment]
Both Jersey and Tyrus are blocked by the Servlet API, too. It is scheduled for the 31/5 release date. Given that and given the 4-week postponement of Jakarta EE 10, we possibly may wait for the Grizzly final.

**Comment by arjantijms** [comment]
> @arjantijms would you conciser to incode https://github.com/eclipse-ee4j/grizzly/pull/2144 into 4.0?

Yes, thanks for the ping!

**Comment by arjantijms** [comment]
>  Given that and given the 4-week postponement of Jakarta EE 10, we possibly may wait for the Grizzly final.

Okay, that's fine. Should you need a Milestone release in central just ping this issue again. Thanks!

**Comment by jansupol** [comment]
Any progress with 4.0?
We would appreciate the M1 in maven central, too. It's not a must, but without it, we won't publish Jersey M4-M6 to maven central. We do not need to publish it, but it would be better.
The priority for us is the 4.0 final.

**Comment by arjantijms** [comment]
@jansupol Yes, there has been progress indeed. The release review completed successfully and we're essentially ready to publish. See https://projects.eclipse.org/projects/ee4j.grizzly/releases/4.0.0

**Comment by jansupol** [comment]
@arjantijms That's great news! When do you think Grizzly is going to be in maven central?

**Comment by jansupol** [comment]
4.0.0 is there.
