### ISSUE TITLE
SpotBugs analysis: Holder.toString() may return null

### ISSUE THREAD

**Issue by ghost** [eclipse-ee4j/glassfish-grizzly#2182]
Would returning `"null"`, rather than `null`, be more idiomatic?

https://github.com/eclipse-ee4j/grizzly/blob/a2ce7775658e11fbccbb9acd32e2daf2b0799f45/modules/grizzly/src/main/java/org/glassfish/grizzly/utils/Holder.java#L70

[toString method may return null](https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#NP_TOSTRING_COULD_RETURN_NULL)
This toString method seems to return null in some circumstances. A liberal reading of the spec could be interpreted as allowing this, but it is probably a bad idea and could cause other code to break. Return the empty string or some other appropriate string rather than null.
 
Since at least 2.3.25.

Consider:

``` java
return obj == null ? "null" : "{" + obj + "}";
```

**Comment by mnriem** [comment]
@DaveJarvis Would you consider "{}" instead as the Holder object itself does exist, but rather it has nothing to hold onto?

**Comment by mnriem** [comment]
@DaveJarvis Can you create a PR for this?

**Comment by ghost** [comment]
> @DaveJarvis Can you create a PR for this?

No, I'm moving off of GitHub soon.
