### ISSUE TITLE
Release Grizzly with fixed module.info

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/glassfish-grizzly#2200]
After Grizzly 4.0.1 has been released, required [changes](https://github.com/eclipse-ee4j/grizzly/pull/2199) were applied.

Any plan for releasing Grizzly with the change?

**Comment by mnriem** [comment]
@jansupol Released as per https://repo1.maven.org/maven2/org/glassfish/grizzly/grizzly-project/4.0.2/. Feel free to close this issue.
